// Generated by Unloop
// Smart TV Control

slint::include_modules!();

fn main() -> Result<(), slint::PlatformError> {
    let app = App::new()?;
    
    // TODO: Wire up callbacks to actual hardware/logic
    app.on_power_toggle_clicked(|| {
        println!("power_toggle clicked");
    });
    
    app.on_mute_toggle_clicked(|| {
        println!("mute_toggle clicked");
    });
    
    app.on_show_guide_clicked(|| {
        println!("show_guide clicked");
    });
    

    
    app.run()
}
