// Generated Data Model

export struct AppData {
    volume-level: float,
    target-volume: float,
    current-channel: string,
    signal-strength: float,
    power-status: string,
    wifi-status: string,
    hdmi-status: string,
    channel-list: string,
    app-list: string,
    screen-brightness: float,
    screen-contrast: float,
    picture-mode: string,
    audio-mode: string,
    auto-volume-enabled: bool,
    ip-address: string,
    sleep-timer: float,
    auto-update-enabled: bool,
    software-version: string,
}
